# Homework 7
#### Cody Costa, David Loi

### Problem 1:

#### Import necessary module(s)

In [33]:
import numpy as np

### Function to generate random symmetric matrix:

In [188]:
''' function to generate 2x2 symmetric matrix whose
    elements are constrained to be between 0 and 10 '''

size: int = 2
max_value: int = 10

def generate_symmetric_matrix(size) -> np.ndarray:

    matrix: np.ndarray = np.zeros([size, size])

    for element in range(size):

        # diagonal matrix
        matrix[element, element] = np.random.randint(0, max_value)

        # fill it such that matrix is symmetric
        filler = np.array([np.random.randint(0, max_value) for e in range(size - element - 1)])

        matrix[element, element + 1:] = filler
        matrix[element + 1:, element] = filler

    return matrix

    # verify the matrix has a nonzero determinant

    # if np.linalg.det(matrix):
    #     return matrix
    
    # else:
    #     generate_symmetric_matrix(size)


#### test that function works:

In [196]:
M: np.ndarray = generate_symmetric_matrix(2)
print(M)

[[3. 6.]
 [6. 9.]]


### Decomposition

use the property that a matrix A can be equated to A = PDP^T where...

#### D = diagonal matrix of eigenvalues
#### P = matrix of eigenvectors

In [160]:
eigenvalues, eigenvectors = np.linalg.eig(M)
print(eigenvalues, '\n')
print(eigenvectors)

[-1.70820393 11.70820393] 

[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


### Find SVD of matrix

In [161]:
U, S, U_T = (np.linalg.svd(M))
print(U, '\n\n', S, '\n\n', U_T)


[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]] 

 [11.70820393  1.70820393] 

 [[-0.52573111 -0.85065081]
 [ 0.85065081 -0.52573111]]


### Define our P and D matrices

In [162]:
# P: np.ndarray = 1 / abs(np.min(eigenvectors)) * eigenvectors
# P

P = eigenvectors
print(P)

[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


### Craft the diagonal matrix of eigenvalues D

In [163]:
D: np.ndarray = np.zeros([size, size])
for idx, val in enumerate(S):
    D[idx, idx] = eigenvalues[idx]

print(D)

[[-1.70820393  0.        ]
 [ 0.         11.70820393]]


In [164]:
''' test our P and D matrices are accurate via A = P D P^T '''

print(P @ D @ P.T, '\n')
print(M)


[[2. 6.]
 [6. 8.]] 

[[2. 6.]
 [6. 8.]]


### More decomposition relations

let's normalize the matrix P (eigenvectors) and establish the relation m @ V == V @ D

In [165]:
P

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [166]:
''' normalize eigenvectors '''

V = np.zeros([size, size])

V[:, 0] = P[:, 0] / np.max(abs(P[:, 0]))
V[:, 1] = P[:, 1] / np.max(abs(P[:, 1]))

In [167]:
V

array([[-1.        , -0.61803399],
       [ 0.61803399, -1.        ]])

In [169]:
''' check for correctness'''

res1 = np.round(M @ V, 2)
res2 = np.round(V @ D, 2)
print(res1, '\n\n', res2)

[[  1.71  -7.24]
 [ -1.06 -11.71]] 

 [[  1.71  -7.24]
 [ -1.06 -11.71]]


#### Given this relation, we can conclude the matrix V are the eigenvectors of m

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


### Problem 2: